### ISSUE TITLE
Disabling dropdown does not work as it should.

### ISSUE THREAD

**Issue by chonla** [couds/react-bulma-components#332] opened 2021-05-21 03:44 UTC
**Describe the bug**
Disabling dropdown does not work as it should.

**To Reproduce**
1. Create `<Dropdown disabled={true}>` with some items.
2. Open the rendered component.

**Expected behavior**
Rendered Dropdown should be disabled, but it is not.

**Versions**
- `react-bulma-components:`: ^3.4.0
- `bulma`: ^0.9.2
- `react`: ^17.0.2
- Browser: Google Chrome 90.0.4430.212

**Comment by kennethnym** [comment] 2021-05-25 14:24
Can you upgrade to v4 and see if the issue persists? Thanks.

**Comment by chonla** [comment] 2021-05-26 14:25
Yes, the problem persists.

AFAIK, the disabled prop is not propagated to <Button> inside.

```
<Button color={color}>
          <span>{current}</span>
          {icon}
</Button>
```

**Comment by kennethnym** [comment] 2021-05-27 20:31
I'll look into it.

**Comment by couds** [comment] 2021-05-28 07:28
Hi @chonla. I was checking the bulma [documentation](https://bulma.io/documentation/components/dropdown/) Iand didn't found a `disabled` state for the dropdown. We can think on maybe add it but for know I prefer not to do it to not divert too much from Bulma.

If you want to add a feature request we can discuss it and see what the community think about. meanwhile I'm closing this due its not a bug

**Closed by couds** 2021-05-28 07:28 UTC
Labels: bug

**Comment by chonla** [comment] 2021-05-28 09:39
@couds I understand what you mean. In my opinion, you can disable the dropdown in bulma by disabling the dropdown-trigger which is a button.

The `<Dropdown>` component itself contain `<Button>` inside and does not allow me to disable.

Any suggestion?

**Comment by couds** [comment] 2021-05-28 12:30
I think that make sense. then let's add a disabled prop to the dropdown that will disable the button.

**Comment by couds** [comment] 2021-05-28 12:46
@chonla released on https://github.com/couds/react-bulma-components/releases/tag/v4.0.6

**Comment by chonla** [comment] 2021-05-28 13:01
Thank you.
